object_detection:
  od_enabled: true
  detection_model: CUSTOM_YOLOLIKE_BOX_OBJECTS
  custom_onnx_input_size: 512
  custom_onnx_file: '/home/roboboat/roboboat_ws/src/mhseals_nav/config/epoch60.onnx'
  custom_class_count: 13

  class_000:
    label: 'black_buoy'
    model_class_id: 0
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_001:
    label: 'black_cross'
    model_class_id: 1
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_002:
    label: 'black_target_boat'
    model_class_id: 2
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_003:
    label: 'black_triangle'
    model_class_id: 3
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_004:
    label: 'blue_buoy'
    model_class_id: 4
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_005:
    label: 'green_buoy'
    model_class_id: 5
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_006:
    label: 'green_light_buoy'
    model_class_id: 6
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_007:
    label: 'green_pole_buoy'
    model_class_id: 7
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_008:
    label: 'red_buoy'
    model_class_id: 8
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_009:
    label: 'red_light_buoy'
    model_class_id: 9
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_010:
    label: 'red_pole_buoy'
    model_class_id: 10
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_011:
    label: 'yellow_buoy'
    model_class_id: 11
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0

  class_012:
    label: 'yellow_target_boat'
    model_class_id: 12
    enabled: true
    confidence_threshold: 20.0
    is_grounded: true
    is_static: false
    tracking_timeout: -1.0
    tracking_max_dist: -1.0
    max_box_width_normalized: -1.0
    min_box_width_normalized: -1.0
    max_box_height_normalized: -1.0
    min_box_height_normalized: -1.0
    max_box_width_meters: -1.0
    min_box_width_meters: -1.0
    max_box_height_meters: -1.0
    min_box_height_meters: -1.0
    object_acceleration_preset: 'DEFAULT'
    max_allowed_acceleration: 100000.0