/**:
  ros__parameters:
    frequency: 80.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: false
    transform_time_offset: 0.3
    predict_to_current_time: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # === MAVROS Odom ===
    odom0: /odom/mavros
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false,  true,   # roll, pitch, yaw
      true,  true,  false,   # vx, vy, vz
      false, false,  true,   # vroll, vpitch, vyaw
      false, false, false    # ax, ay, az
    ]

    # === MAVROS IMU ===
    imu0: /imu/filtered
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    
    imu0_config: [
      false, false, false,   # position
      false, false, false,   # orientation (disable if VIO provides it)
      true,  true,  true,    # angular velocity (gyro)
      true,  true,  true     # linear acceleration
    ]

    # # === DLIO ===
    # odom0: /odom/dlio
    # odom0_differential: false
    # odom0_relative: false
    # odom0_queue_size: 10
    # odom0_config: [
    #   true,  true,  false,   # x, y, z
    #   false, false,  true,   # roll, pitch, yaw
    #   true,  true,  false,   # vx, vy, vz
    #   false, false,  true,   # vroll, vpitch, vyaw
    #   false, false, false    # ax, ay, az
    # ]

    # # === ZED Odom VIO ===
    # odom1: /front_camera/odom
    # odom1_differential: false
    # odom1_relative: false
    # odom1_queue_size: 10
    # odom1_config: [
    #   true,  true,  false,   # x, y, z
    #   false, false,  true,   # roll, pitch, yaw
    #   true,  true,  false,   # vx, vy, vz
    #   false, false,  true,   # vroll, vpitch, vyaw
    #   false, false, false    # ax, ay, az
    # ]