/**:
  ros__parameters:
    system_id: 42
    component_id: 67 

    local_position:
      frame_id: odom
      tf:
        send: true
        frame_id: odom
        child_frame_id: base_link

    global_position:
      tf:
        send: false

    imu:
      frame_id: imu_link
      
    gps:
      frame_id: gps_link