rtabmap:
  ros__parameters:
    # Sensors
    subscribe_depth: false
    subscribe_rgb: true
    subscribe_rgbd: false
    subscribe_stereo: false
    subscribe_scan: true
    
    # Frames
    frame_id: "base_link"
    map_frame_id: "map"
    odom_frame_id: "odom"
    
    # Odometry
    odom_sensor_sync: false
    wait_for_transform: 0.3
    approx_sync: true
    publish_tf: false

    sync_queue_size: 10
    topic_queue_size: 10

    # 2D map parameters
    Grid/2D_map: "true"
    Grid/Sensor: "false"
    Grid/FromDepth: "false"
    Grid/MaxGroundHeight: "1.0"
    Grid/MinGroundHeight: "-1.0"
    Grid/MaxObstacleHeight: "3.0"
    Grid/CellSize: "0.05"
    Grid/PreVoxelFiltering: "false"
    Grid/3D: "false"
    Mem/SaveDepth16Format: "true"
    Mem/DepthCompressionFormat: ".rvl"

rgbd_odometry:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: odom
    publish_tf: false
    publish_null_when_lost: false
    guess_frame_id: ""
    wait_for_transform: 0.3
    
    # Visual odometry parameters
    Odom/Strategy: "0"  # Frame-to-Map = 0, Frame-to-Frame = 1
    Odom/ResetCountdown: "1"
    Odom/MinInliers: "15"  # Lower from default 20 if features are sparse
    OdomF2M/MaxSize: "2000"
    Vis/MinInliers: "15"
    Vis/InlierDistance: "0.1"
    Vis/MaxDepth: "10.0"
    Vis/CorNNDR: "0.8"